### PR TITLE
Trying to remove deprecated metrics

### PR DESCRIPTION
**Pull request by LiohAu**
I am not sure for the LINE. But for the FILES, the changes is there : https://github.com/SonarSource/sonarqube/commit/f6b2a269c44043f1c230b646dbb8662aed3fa5a4#diff-958438b627eede67724e05feb7d35e69L89

### CODE REVIEW

**Comment by LiohAu** [comment]
Should fix #212

**Comment by silverhammermba** [comment]
You need to make the same change in the objclang side.

**Comment by sindhuby** [comment]
When will this PR be merged ? is there a timeline. since i dont want to go about changing a thrid party library.

**Comment by gaelfoppolo** [comment]
PRhttps://github.com/Backelite/sonar-swift/pull/238 does exactly the same, and also apply on Objective-C
Closing this one.

**Pull request closed without merging**
