### PR TITLE
Improve tests result handling

### PR DESCRIPTION
**Pull request by viteinfinite**
This PR aims to improve the handling of test results.
In particular: 
- tests can now be looked for in subfolders. For instance, `MyProjectTests/Folder/SomeTests.swift` is now correctly indexed
- A new `sonar.junit.include` configuration is now available in the `project.properties` file, allowing user to override the pattern used for locating junit files. This is particularly useful when running Sonar along with Fastlane / xcpretty, when the output file is `report.junit`, instead of the `TEST-XXX.xml` which is currently the only supported option.

Also, specs for the features above have been added.

Thank you for the good work!

### CODE REVIEW

**Comment by zippy1978** [comment]
Hi,

As soon as I merge your PR, if I launch an analysis unit test count of my repot is reset to 0.
I tested on SonarQube 5.2...

Do you notice the same behavior ?

Gilles

**Comment by viteinfinite** [comment]
I cannot actually reproduce the problem: _without_ the PR my unit test count figure was incorrect. 
It's obvious there is a configuration I did not take into account. 
Could you provide me with your test project? Thank you!

**Comment by viteinfinite** [comment]
Hey, any hint about how to reproduce the issue? Thanks!

**Comment by zippy1978** [comment]
Hi,

Here is the projects I used : https://dl.dropboxusercontent.com/u/26978903/Swift2Test.zip

**Comment by viteinfinite** [comment]
I'll check it out, thank you very much!

**Comment by viteinfinite** [comment]
@zippy1978 I tried with your use case and I added one more test to the specs. That said, I cannot reproduce the issue. Tests were performed under 5.4 through 5.6 LTS.
This opens a question, though. Which is the minimum SonarQube version we want to support?

**Comment by zippy1978** [comment]
Hi @viteinfinite,

Thanks.

I will have a look and test again :)

The minimum supported version should be 4.5.7 (former LTS).

**Comment by skromberg** [comment]
I've tested the Swift2Test Project in our test environment (Sonar Version 5.6 with your patched plugin) without success. Dashboard shows 43,9 % test coverage but 0 tests at all.

**Comment by zippy1978** [comment]
Hi,
The minimum version I want to support is 4.5.x.
I tested again with 5.2 but still have the issue.

I will have a look at it later.

Regard

**Comment by zippy1978** [comment]
Hi,

Since the rewriting for SonarQube 6 support, I think this PR is out of date now.
I close it.

**Comment by viteinfinite** [comment]
Alright, I'll check if my usecase is fixed.
Thanks for letting me know!

**Comment by viteinfinite** [comment]
Everything works like a charm now! 🙌

**Comment by zippy1978** [comment]
Glad to know it !

Thanks 👍

**Pull request closed without merging**
