### PR TITLE
7.3 support, stax removal, etc

### PR DESCRIPTION
**Pull request by bcolvin**
#176 is a much more reasonable set of changes for just 7.3 support. This is quite a substantial changeset, reject if its not going in the right direction

### CODE REVIEW

**Comment by zippy1978** [comment]
Hi @bcolvin ,

Thank you very much !
I'm currently integrating your PR.

The only problem I see is that unit test reports seems broken (surefire).
I'll investigate on this, but maybe you have an idea ?

Regards,
Gilles

**Comment by bcolvin** [comment]
I can look into fixing it. Could you post the error/relevant output from console or if none maybe a sample report if you think its an issue with reading in the output

**Comment by zippy1978** [comment]
Hi @bcolvin,

Actually there is no error : since you refactored the SurfireSensor unit test reports are not parsed anymore (did not have time to figure out why yet).
The result is that the only thing available on the Sonar report is the coverage rate : number of unit tests is missing (as well as details on tests).

I had a look at the code and it also seems that the part where test source files are matched with test cases is missing.

**Comment by bcolvin** [comment]
Hi @zippy1978 ,

Ah might be related to this code I removed. This "MutableTestPlan" was deprecated and there was no replacement. Let me know if you figure it out.
`
protected void saveResults(InputFile testFile, UnitTestClassReport report) {
        for (UnitTestResult unitTestResult : report.getResults()) {
            MutableTestPlan testPlan = perspectives.as(MutableTestPlan.class, testFile);
            if (testPlan != null) {
                testPlan.addTestCase(unitTestResult.getName())
                        .setDurationInMs(Math.max(unitTestResult.getDurationMilliseconds(), 0))
                        .setStatus(TestCase.Status.of(unitTestResult.getStatus()))
                        .setMessage(unitTestResult.getMessage())
                        .setType(TestCase.TYPE_UNIT)
                        .setStackTrace(unitTestResult.getStackTrace());
            }
        }
    }
`

**Comment by gaelfoppolo** [comment]
Any update on these issues?

**Pull request merged**
