### PR TITLE
SonarQube 6 support

### PR DESCRIPTION
**Pull request by Alex009**
Hello.
I've done some fixes for support SonarQube 6 and up. Now minimal sonar version to 5.0.
I've checked it on my project, but need to test some others.

Also I've attached compiled plugin for simple testing without recompile.
[backelite-sonar-swift-plugin-0.2.4.jar.zip](https://github.com/Backelite/sonar-swift/files/467709/backelite-sonar-swift-plugin-0.2.4.jar.zip)

### CODE REVIEW

**Comment by Alex009** [comment]
Strange...I've check build with travis on fork repo and all ok - [travis build](https://travis-ci.org/icerockdev/sonar-swift/builds/159481846)

**Comment by zippy1978** [comment]
Thanks a lot !
I merge it and I will do some extra checks on my side as well.

**Comment by zippy1978** [comment]
Hi again,

On my test project I get a **Unknow input path type: null** exception.
This occurs on line **Resource resource = context.getResource(inputFile);** in **SwiftSureFireParser.java#getUnitTestResource**.

Is test reporting parsing ok on your side ?

**Comment by Alex009** [comment]
@zippy1978 yes, my tests parsed and reported in sonarqube. I get same error in development and fix it via searh test class file by mask "**/<TestClassNameWithoutModule>.swift"
maybe name of your XCTestCase class not equal name of file contained this class?
Can you give your "sonar-reports" folder for me to improve parsing?

**Comment by zippy1978** [comment]
@Alex009 my test project is dead simple and here : https://dl.dropboxusercontent.com/u/26978903/Swift2Test.zip

I'm also having a look on my side...

**Comment by Alex009** [comment]
@zippy1978 your sonar-project.properties incorrect. Tests directories not all - should be
```
sonar.tests=Swift2TestTests,Swift2TestUITests
```
instead of 
```
sonar.tests=Swift2TestTests
```
Plugin try found UITests class and failed because this class not loaded in sonar

**Comment by zippy1978** [comment]
Thanks a lot @Alex009 !

**Pull request merged**
