### PR TITLE
Adding SwiftLint 0.18.1 support

### PR DESCRIPTION
**Pull request by marcus174**
This pull request updates the sonar-swift rules to align to the currnet version of SwiftLint 0.18.1.

### CODE REVIEW

**Comment by tungdt-gem** [comment]
Can someone merge this request and create new release please? 

Thanks so much!

**Comment by pbernery** [comment]
Thanks!

**Comment by pbernery** [comment]
Version [0.3.4](https://github.com/Backelite/sonar-swift/releases/tag/0.3.4) has been released.

**Comment by tungdt-gem** [comment]
Thanks for your help @pbernery 👍

**Pull request merged**
